In [ ]:
# use case 1 (college)

from dataframe_generator import df_gen
import numpy as np
import pandas as pd 

non_us_countries = [
    "Canada", "Mexico", "India", "China", "United Kingdom",
    "Germany", "France", "Brazil", "Nigeria", "South Korea"
]

gen = df_gen(10, random_state=10)
gen.add_column("id", ("prefix_id", "STU", 5, True))
gen.add_column("names", ("names",))
gen.add_column("student_email", ("email", ["school.edu"]))
gen.add_column("phone", ("phone",[813,833,767]))
gen.add_column("state", ("state", {"missing": 0.25}))
gen.add_column(
    "country",
    (
        "computed",
        lambda df: pd.Series(
            np.where(
                df["state"].notna(),
                "United States",
                np.random.choice(non_us_countries, size=len(df))
            ),
            dtype="object"
        ),
        ["state"]
    )
)
gen.add_column("age", ("int", 18, 22))
gen.add_column("dob", ("dob_from_age", "age"))
gen.add_column("major", ("category", ["art", "math", "music", "biology", "chemistry", "english", "political science", "psychology"]))
gen.add_column("GPA", ("normal_clip", 3,1.5, 0,4, {"round": 2}))
gen.add_column("major_GPA", ("decimals", 2, 4))
gen.add_column(
    "year",
    (
        "computed",
        lambda df: pd.Series(
            np.select(
                [
                    df["age"].between(18, 19),
                    df["age"].between(19, 20),
                    df["age"].between(20, 21),
                ],
                [
                    "Freshman",
                    "Sophomore",
                    "Junior",
                ],
                default="Senior"
            ),
            dtype="object"
        ),
        ["age"]
    )
)
df = gen.build()

df.head(10)

,id,first_name,last_name,student_email,phone,state,country,age,dob,major,GPA,major_GPA,year
0,STU33226,Thomas,Tucker,thomas.tucker@school.edu,(767) 883-9492,NaN,Nigeria,21,2004-08-04,music,3.94,0.794198,Junior
1,STU64804,Dennis,Nichols,dennis.nichols@school.edu,(833) 345-7163,AZ,United States,22,2003-04-26,math,2.53,1.476054,Senior
2,STU39763,Evan,Peterson,evan.peterson@school.edu,(767) 449-4465,CA,United States,22,2003-09-14,biology,3.55,0.740415,Senior
3,STU51270,Hannah,Wood,hannah.wood@school.edu,(833) 577-4224,VT,United States,21,2004-04-22,psychology,0.87,1.692804,Junior
4,STU09698,Margot,Robertson,margot.robertson@school.edu,(767) 997-3548,WI,United States,19,2006-04-20,psychology,2.69,1.798696,Freshman
5,STU05948,Vanessa,Khan,vanessa.khan@school.edu,(813) 760-1767,MO,United States,22,2003-10-07,biology,1.90,3.425521,Senior
6,STU27955,Diane,Payne,diane.payne@school.edu,(833) 946-4778,LA,United States,20,2005-12-04,english,4.00,2.934372,Sophomore
7,STU55001,Camila,Sanders,camila.sanders@school.edu,(833) 316-9270,MS,United States,22,2003-09-10,biology,1.89,3.212886,Senior
8,STU50875,Linda,Barnes,linda.barnes@school.edu,(833) 853-7522,MI,United States,21,2004-07-23,math,4.00,3.079115,Junior
9,STU47755,Theresa,Jacobs,theresa.jacobs@school.edu,(833) 775-9817,NaN,United Kingdom,18,2007-03-16,psychology,3.89,2.016294,Freshman

In [ ]:
# use case 2 (orders)

from dataframe_generator import df_gen
import numpy as np
import pandas as pd 

gen_df = df_gen(rows=10, random_state=2)


gen_df.add_column("order_id", ("id", 0))
gen_df.add_column("customer_code", ("prefix_id", "CUST", 4, True))
gen_df.add_column("customer_id", ("alphanumeric_id", 8, False))
gen_df.add_column("customer_initials", ("string", 3, "upper"))
gen_df.add_column("num_products", ("int", 1, 20))
gen_df.add_column("price", ("correlated", "num_products", 3, 0.5))
gen_df.add_column("shipping", ("int_list", [1,1.5,2], [0.25,0.5,0.25]))
gen_df.add_column("delivered", ("bernoulli", 0.65))
gen_df.add_column("pct_paid", ("percent", 10,2, True))
gen_df.add_column("num_payment_methods", ("int_list", [1,2,3], [0.9, 0.06, 0.04]))
gen_df.add_column("order_date", ("datetime", '2025-01-01', '2025-12-31'))
gen_df.add_column("delivered_from", ("category_prob", ['Amazon', 'Website', 'Store'], [0.4, 0.5, 0.1]))
gen_df.add_column("survey_completion", ("beta", 3, 5, 100, {'missing':0.7}))  #missing used here
df = gen_df.build()

df.head(10)

,order_id,customer_code,customer_id,customer_initials,num_products,price,shipping,delivered,pct_paid,num_payment_methods,order_date,delivered_from,survey_completion
0,0,CUST7878,XvbQg6hz,MHA,11,33.337494,1.5,False,82.528476,1,2025-01-24 22:20:32,Store,NaN
1,1,CUST3224,2IAUiMsC,YFI,2,6.140348,1.5,True,93.340955,1,2025-07-28 02:56:45,Website,NaN
2,2,CUST1919,oeKaVykC,UBI,2,6.654246,1.5,False,93.272301,1,2025-01-28 00:30:46,Website,NaN
3,3,CUST4432,7by5g7ph,HOZ,10,29.648856,2.0,False,88.208789,1,2025-04-28 18:13:15,Amazon,7.589618
4,4,CUST4835,tLSp1Mmq,DPS,6,18.355253,1.5,True,97.333515,1,2025-12-30 06:52:30,Website,NaN
5,5,CUST4895,LM2Brepc,XCB,14,41.410423,1.5,True,92.806687,1,2025-11-26 16:35:48,Amazon,29.375796
6,6,CUST7269,q33tz5ha,HVB,14,42.185282,2.0,False,91.412906,1,2025-04-27 09:15:57,Website,NaN
7,7,CUST1451,Y05doZzV,DRE,16,47.823469,2.0,True,70.154002,1,2025-10-23 13:11:44,Website,NaN
8,8,CUST1742,izdPJRjZ,QNI,4,12.088512,2.0,True,96.752771,2,2025-04-06 08:14:57,Amazon,NaN
9,9,CUST4628,lh81ZCo6,GSJ,10,29.734927,1.0,True,86.675168,1,2025-06-22 00:07:58,Website,29.776041

In [5]:
# use case 3 (distributions)

from dataframe_generator import df_gen
import numpy as np
import pandas as pd 


gen_df = df_gen(rows=10, random_state=5)

# add cols
gen_df.add_column("normal", ("normal", 10, 1))
gen_df.add_column("normal_clip", ("normal_clip", -10, 20, -30, 30))
gen_df.add_column("bernoulli", ("bernoulli",0.5))
gen_df.add_column("beta", ("beta", 3, 1, 10))
gen_df.add_column("poisson", ("poisson", 7))
gen_df.add_column("lognormal", ("lognormal", 3, 1))
gen_df.add_column("gamma", ("gamma", 5,4))
gen_df.add_column("exponential", ("exponential", 3))
gen_df.add_column("timeseries", ("trend", 0, 56, 0.5))
gen_df.add_column("correlated", ("correlated", "normal", 3, 10))
df = gen_df.build()


df.head(10)

,normal,normal_clip,bernoulli,beta,poisson,lognormal,gamma,exponential,timeseries,correlated
0,10.441227,-30.000000,True,8.435433,4,32.902797,9.914307,1.363965,1.036808,30.385358
1,9.669130,-14.097530,True,8.468766,7,33.131594,25.679221,1.949926,56.354899,28.450679
2,12.430771,-17.176579,True,6.202640,7,44.363747,26.644232,2.343251,112.373576,28.398106
3,9.747908,2.069432,True,7.354809,4,23.825691,16.338908,0.924594,168.731548,16.234209
4,10.109610,-30.000000,True,7.655778,6,3.477310,22.907126,0.432871,224.869224,44.350496
5,11.582481,-24.003581,False,8.234623,7,37.723999,45.451580,1.078119,280.732602,39.398453
6,9.090768,13.027820,False,6.874866,11,33.060169,8.569742,0.440215,336.606142,16.621977
7,9.408363,27.146620,True,7.012921,8,55.597465,18.520625,1.146858,391.682674,32.129296
8,10.187603,-30.000000,True,6.719741,6,8.615228,15.605418,3.410650,447.200151,33.618811
9,9.670130,2.896950,True,9.729470,4,249.836732,8.878498,2.758948,504.438576,34.228885