In [1]:
# use case 1 (all column types)
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)


from dataframe_generator import df_gen

gen = (
    df_gen(rows=50, random_state=14)

    
    .add_column("row_id", ("id",))
    .add_column("user_code", ("prefix_id", "USR", 4, True))
    .add_column("session_id", ("alphanumeric_id", 8))
    .add_column("group", ("manual", ["A", "B", "C"], True))
    .add_column("age", ("int", 18, 65))
    .add_column("children", ("int_list", [0, 1, 2, 3], [0.4, 0.3, 0.2, 0.1]))
    .add_column("score_uniform", ("uniform", 0, 100, {"round": 1}))
    .add_column("completion_rate", ("percent", 2, 5, True))
    .add_column("is_active", ("bool",))
    .add_column("converted", ("bernoulli", 0.3))
    .add_column("plan", ("category", ["Free", "Standard", "Premium"]))
    .add_column("region", ("category_prob",
        ["North", "South", "East", "West"],
        [0.25, 0.25, 0.25, 0.25]
    ))
    .add_column("promo_code", ("string", 6, "upper"))
    .add_column("name", ("names", True))
    .add_column("email", ("email",))
    .add_column("phone", ("phone", [813, 305, 212], "dashes"))
    .add_column("state", ("state", True))
    .add_column("country", ("country", "name", True))
    .add_column("signup_date", ("date", "2022-01-01", "2023-12-31"))
    .add_column("last_seen", ("datetime", "2023-01-01", "2024-01-01"))
    .add_column("dob", ("dob_from_age", "age"))
    .add_column("age_check", ("age_from_dob", "dob"))
    .add_column("income", ("lognormal", 10, 0.6, {"round": 2}))
    .add_column("noise_normal", ("normal", 0, 1))
    .add_column("bounded_score", ("normal_clip", 70, 10, 0, 100))
    .add_column("tickets_opened", ("poisson", 3))
    .add_column("probability", ("beta", 2, 5, 1))
    .add_column("wait_time", ("exponential", 5))
    .add_column("gamma_metric", ("gamma", 2, 3))
    .add_column("trend_value", ("trend", 100, 0.8, 5))
    .add_column("spend_estimate", ("correlated", "income", 0.02, 200))
    .add_column("vip_flag", ("conditional", "plan", "Premium", 1, 0))
    .add_column(
        "income_to_age_ratio",
        ("computed", lambda df: df["income"] / df["age"], ["income", "age"])
    )
    .add_column("income_roll_mean", ("rolling_mean", "income", 5))
    .add_column("income_roll_sum", ("rolling_sum", "income", 5))
    .add_column("income_roll_std", ("rolling_std", "income", 5))
    .add_column("income_roll_max", ("rolling_max", "income", 5))
    .add_column("income_roll_min", ("rolling_min", "income", 5))
    .add_column("income_z", ("zscore", "income"))
    .add_column(
        "income_bin",
        ("bin", "income", [0, 30000, 70000, 150000, 1_000_000],
        ["Low", "Mid", "High", "Very High"])
    )
    .add_column("income_pct_change", ("pct_change", "income"))
)

df = gen.build()
df.tail(10)

,row_id,user_code,session_id,group,age,children,score_uniform,completion_rate,is_active,converted,plan,region,promo_code,first_name,last_name,email,phone,state,country,signup_date,last_seen,dob,age_check,income,noise_normal,bounded_score,tickets_opened,probability,wait_time,gamma_metric,trend_value,spend_estimate,vip_flag,income_to_age_ratio,income_roll_mean,income_roll_sum,income_roll_std,income_roll_max,income_roll_min,income_z,income_bin,income_pct_change
40,41,USR6115,QfrMXZeN,A,60,2,61.8,48.388424,True,True,Free,North,TUVWHL,Nancy,Vega,nancy.vega@outlook.com,305-429-6910,NJ,Germany,2023-02-22,2023-02-03 01:06:51,1965-03-20,60,79290.66,-0.435453,69.358586,2,0.332832,15.497135,6.665690,126.596910,1298.601556,0,1321.511000,40734.574,203672.87,31524.015342,79290.66,8777.51,2.212887,High,1.540449
41,42,USR0774,DLGVySbe,C,18,0,13.2,29.336680,True,False,Standard,South,INODYC,Brian,Montoya,brian.montoya@yahoo.com,813-744-7876,NM,Indonesia,2022-06-07,2023-04-06 23:07:07,2007-10-20,18,15704.04,-0.390784,68.494207,1,0.180521,0.065270,5.909430,128.576539,625.166742,0,872.446667,42119.880,210599.40,29877.803226,79290.66,15704.04,-0.743251,Low,-0.801943
42,43,USR3284,CMbGwf3o,C,32,1,74.9,22.806762,True,True,Free,West,GVAISV,Miguel,Long,miguel.long@outlook.com,813-762-2557,AK,South Korea,2023-07-15,2023-11-28 20:20:15,1993-10-19,32,6463.85,0.163433,60.088047,3,0.105628,1.111460,4.272959,127.554303,-25.788326,0,201.995313,29734.492,148672.46,29090.097482,79290.66,6463.85,-1.172827,Low,-0.588396
43,44,USR6609,sUYSO1Bn,B,33,1,5.3,5.824356,True,True,Free,East,QFCBHZ,Jeremy,Cooper,jeremy.cooper@gmail.com,305-440-5883,NC,United States,2022-03-18,2023-04-16 11:57:57,1992-05-21,33,48273.13,-0.786979,69.829464,5,0.367804,7.456062,16.460258,132.552886,756.175676,0,1462.822121,36188.592,180942.96,28860.765396,79290.66,6463.85,0.770884,Mid,6.468170
44,45,USR4485,n88cG8Wb,A,55,2,72.1,24.854816,False,True,Standard,South,DSEABC,Jared,Howell,jared.howell@gmail.com,212-588-1313,CO,France,2023-09-19,2023-09-11 04:50:54,1970-09-07,55,15028.25,-1.303593,63.749079,4,0.475824,7.906950,5.777436,135.722200,48.241974,0,273.240909,32951.986,164759.93,30423.607050,79290.66,6463.85,-0.774669,Low,-0.688683
45,46,USR4700,v41RDWwq,B,19,0,92.5,38.047009,False,False,Free,East,TTPRWK,Diana,Wilson,diana.wilson@outlook.com,813-474-2885,ND,United States,2023-09-25,2023-04-15 17:28:47,2007-01-06,19,26975.78,-0.227408,75.693028,2,0.165201,1.106958,3.373114,131.610618,882.483382,0,1419.777895,22489.010,112445.05,16151.288338,48273.13,6463.85,-0.219229,Low,0.795005
46,47,USR4678,9TLH2mPT,C,37,3,97.3,49.080298,True,True,Free,North,DNJDZT,Martha,Williams,martha.williams@yahoo.com,305-741-9656,NY,United States,2023-11-19,2023-04-06 03:57:17,1988-08-03,37,23696.95,0.031416,87.994014,2,0.152213,8.264594,2.390473,134.216638,639.148281,0,640.458108,24087.592,120437.96,15701.134028,48273.13,6463.85,-0.371661,Low,-0.121547
47,48,USR0899,PHBFk8qu,A,39,0,57.3,47.238693,False,False,Standard,South,FYQCGU,Adeline,Graham,adeline.graham@outlook.com,813-989-3929,MN,Japan,2023-09-24,2023-01-14 10:05:05,1986-09-27,39,51502.99,-0.901308,60.925382,5,0.179064,16.114520,1.292743,136.035488,1014.729185,0,1320.589487,33095.420,165477.10,15979.716659,51502.99,15028.25,0.921040,Mid,1.173402
48,49,USR5451,J2erLVPi,C,56,3,93.7,11.481480,False,False,Standard,West,UGZGPW,Victoria,Diaz,victoria.diaz@outlook.com,813-408-2506,SD,Germany,2022-05-11,2023-06-21 17:56:25,1969-08-06,56,45979.62,0.021798,57.131554,7,0.199373,1.450935,6.926568,137.170945,1220.572684,0,821.064643,32636.718,163183.59,15459.568794,51502.99,15028.25,0.664259,Mid,-0.107244
49,50,USR5234,flHjKU4p,A,21,0,73.5,29.993043,False,False,Free,South,QRVXYF,Carter,Morgan,carter.morgan@yahoo.com,813-698-4443,KS,China,2022-11-18,2023-03-12 15:26:05,2004-05-02,21,3844.61,0.617220,84.791160,4,0.440297,6.826822,10.023441,142.411582,3.173320,0,183.076667,30399.990,151999.95,19038.813292,51502.99,3844.61,-1.294595,Low,-0.916384

In [6]:
# use case 2 (college)

from df_gen import df_gen
import numpy as np
import pandas as pd 

non_us_countries = [
    "Canada", "Mexico", "India", "China", "United Kingdom",
    "Germany", "France", "Brazil", "Nigeria", "South Korea"
]

gen = df_gen(10, random_state=10)
gen.add_column("id", ("prefix_id", "STU", 5, True))
gen.add_column("names", ("names",))
gen.add_column("student_email", ("email", ["school.edu"]))
gen.add_column("phone", ("phone",[813,833,767]))
gen.add_column("state", ("state", {"missing": 0.25}))
gen.add_column(
    "country",
    (
        "computed",
        lambda df: pd.Series(
            np.where(
                df["state"].notna(),
                "United States",
                np.random.choice(non_us_countries, size=len(df))
            ),
            dtype="object"
        ),
        ["state"]
    )
)
gen.add_column("age", ("int", 18, 22))
gen.add_column("dob", ("dob_from_age", "age"))
gen.add_column("major", ("category", ["art", "math", "music", "biology", "chemistry", "english", "political science", "psychology"]))
gen.add_column("GPA", ("normal_clip", 3,1.5, 0,4, {"round": 2})) #rounding used here
gen.add_column("major_GPA", ("decimals", 2, 4))
gen.add_column(
    "year",
    (
        "computed",
        lambda df: pd.Series(
            np.select(
                [
                    df["age"].between(18, 19),
                    df["age"].between(19, 20),
                    df["age"].between(20, 21),
                ],
                [
                    "Freshman",
                    "Sophomore",
                    "Junior",
                ],
                default="Senior"
            ),
            dtype="object"
        ),
        ["age"]
    )
)
df = gen.build()

df.head(10)

,id,first_name,last_name,student_email,phone,state,country,age,dob,major,GPA,major_GPA,year
0,STU33226,Thomas,Tucker,thomas.tucker@school.edu,(767) 883-9492,NaN,Nigeria,21,2004-08-11,music,3.94,2.397099,Junior
1,STU64804,Dennis,Nichols,dennis.nichols@school.edu,(833) 345-7163,AZ,United States,22,2003-05-03,math,2.53,2.738027,Senior
2,STU39763,Evan,Peterson,evan.peterson@school.edu,(767) 449-4465,CA,United States,22,2003-09-21,biology,3.55,2.370208,Senior
3,STU51270,Hannah,Wood,hannah.wood@school.edu,(833) 577-4224,VT,United States,21,2004-04-29,psychology,0.87,2.846402,Junior
4,STU09698,Margot,Robertson,margot.robertson@school.edu,(767) 997-3548,WI,United States,19,2006-04-27,psychology,2.69,2.899348,Freshman
5,STU05948,Vanessa,Khan,vanessa.khan@school.edu,(813) 760-1767,MO,United States,22,2003-10-14,biology,1.90,3.712761,Senior
6,STU27955,Diane,Payne,diane.payne@school.edu,(833) 946-4778,LA,United States,20,2005-12-11,english,4.00,3.467186,Sophomore
7,STU55001,Camila,Sanders,camila.sanders@school.edu,(833) 316-9270,MS,United States,22,2003-09-17,biology,1.89,3.606443,Senior
8,STU50875,Linda,Barnes,linda.barnes@school.edu,(833) 853-7522,MI,United States,21,2004-07-30,math,4.00,3.539557,Junior
9,STU47755,Theresa,Jacobs,theresa.jacobs@school.edu,(833) 775-9817,NaN,United Kingdom,18,2007-03-23,psychology,3.89,3.008147,Freshman

In [7]:
# use case 3 (orders)

from dataframe_generator import df_gen
import numpy as np
import pandas as pd 

gen_df = df_gen(rows=10, random_state=1)


gen_df.add_column("order_id", ("id", 0))
gen_df.add_column("customer_code", ("prefix_id", "CUST", 4, True))
gen_df.add_column("customer_id", ("alphanumeric_id", 8, False))
gen_df.add_column("customer_initials", ("string", 3, "upper"))
gen_df.add_column("num_products", ("int", 1, 20))
gen_df.add_column("price", ("correlated", "num_products", 3, 0.5))
gen_df.add_column("shipping", ("int_list", [1,1.5,2], [0.25,0.5,0.25]))
gen_df.add_column("delivered", ("bernoulli", 0.65))
gen_df.add_column("pct_paid", ("percent", 10,2, True))
gen_df.add_column("num_payment_methods", ("int_list", [1,2,3], [0.9, 0.06, 0.04]))
gen_df.add_column("order_date", ("datetime", '2025-01-01', '2025-12-31'))
gen_df.add_column("delivered_from", ("category_prob", ['Amazon', 'Website', 'Store'], [0.4, 0.5, 0.1]))
gen_df.add_column("survey_completion", ("beta", 3, 5, 100, {'missing':0.7}))  #missing used here
df = gen_df.build()

df.head(10)

,order_id,customer_code,customer_id,customer_initials,num_products,price,shipping,delivered,pct_paid,num_payment_methods,order_date,delivered_from,survey_completion
0,0,CUST9953,WcmMstLL,BNB,18,53.582108,1.5,False,97.436159,1,2025-10-11 03:05:28,Amazon,NaN
1,1,CUST3850,J54mFiYj,VZY,7,20.565249,1.5,False,63.931969,1,2025-05-21 04:30:06,Amazon,NaN
2,2,CUST4962,3I9g4Vis,TSQ,10,30.455647,1.5,False,94.269784,2,2025-06-20 20:01:22,Amazon,NaN
3,3,CUST3886,E3deNh5k,ZGP,16,47.745691,1.5,True,95.320439,1,2025-03-30 12:37:37,Website,NaN
4,4,CUST5437,yP54MeLs,GDR,7,19.794899,1.5,True,74.220936,1,2025-07-21 21:28:30,Website,NaN
5,5,CUST8517,rb0ypdLP,ZZR,13,39.130877,2.0,True,91.771993,1,2025-01-06 12:19:03,Store,NaN
6,6,CUST2041,jMFOnMIV,FJM,10,29.592004,1.5,True,87.360812,1,2025-10-13 23:22:40,Store,10.247235
7,7,CUST1989,pSWgCkAS,QEO,2,6.616291,1.5,False,84.131073,1,2025-05-21 06:37:45,Website,NaN
8,8,CUST1933,PNLLw5eg,BFK,3,9.077136,2.0,True,76.266924,1,2025-12-09 05:17:11,Amazon,53.281377
9,9,CUST9984,DeArzWRQ,AWU,12,36.377350,1.5,True,84.708558,1,2025-11-19 17:31:18,Website,48.062624

In [8]:
# use case 4 (distributions)

from dataframe_generator import df_gen
import numpy as np
import pandas as pd 


gen_df = df_gen(rows=10, random_state=5)

# add cols
gen_df.add_column("normal", ("normal", 10, 1))
gen_df.add_column("normal_clip", ("normal_clip", -10, 20, -30, 30))
gen_df.add_column("bernoulli", ("bernoulli",0.5))
gen_df.add_column("beta", ("beta", 3, 1, 10))
gen_df.add_column("poisson", ("poisson", 7))
gen_df.add_column("lognormal", ("lognormal", 3, 1))
gen_df.add_column("gamma", ("gamma", 5,4))
gen_df.add_column("exponential", ("exponential", 3))
gen_df.add_column("timeseries", ("trend", 0, 56, 0.5))
gen_df.add_column("correlated", ("correlated", "normal", 3, 10))
df = gen_df.build()


df.head(10)

,normal,normal_clip,bernoulli,beta,poisson,lognormal,gamma,exponential,timeseries,correlated
0,10.441227,-30.000000,True,8.435433,4,32.902797,9.914307,1.363965,1.036808,30.385358
1,9.669130,-14.097530,True,8.468766,7,33.131594,25.679221,1.949926,56.354899,28.450679
2,12.430771,-17.176579,True,6.202640,7,44.363747,26.644232,2.343251,112.373576,28.398106
3,9.747908,2.069432,True,7.354809,4,23.825691,16.338908,0.924594,168.731548,16.234209
4,10.109610,-30.000000,True,7.655778,6,3.477310,22.907126,0.432871,224.869224,44.350496
5,11.582481,-24.003581,False,8.234623,7,37.723999,45.451580,1.078119,280.732602,39.398453
6,9.090768,13.027820,False,6.874866,11,33.060169,8.569742,0.440215,336.606142,16.621977
7,9.408363,27.146620,True,7.012921,8,55.597465,18.520625,1.146858,391.682674,32.129296
8,10.187603,-30.000000,True,6.719741,6,8.615228,15.605418,3.410650,447.200151,33.618811
9,9.670130,2.896950,True,9.729470,4,249.836732,8.878498,2.758948,504.438576,34.228885

In [9]:
# use case 5 (random demographics - to show schema and missing)

from dataframe_generator import df_gen
import numpy as np
import pandas as pd 

gen = (
    df_gen(rows=100, random_state=2)
    .add_column("id", ("id",))
    .add_column("age", ("int", 18, 65, {"missing": 0.05}))
    .add_column("income", ("lognormal", 10, 0.6, {"round": 2}))
    .add_column("income_2", ("lognormal", 20, 0.7, {"missing":0.25, "round":3}))
)
schema = gen.describe_schema()
print(schema)

     column       type parameters  missing_pct  rounding
0        id         id         ()         0.00       NaN
1       age        int   (18, 65)         0.05       NaN
2    income  lognormal  (10, 0.6)         0.00       2.0
3  income_2  lognormal  (20, 0.7)         0.25       3.0